version: '3.8'
services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: kafeindb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  spring-boot-app:
    image: kafein-backend:latest
    container_name: spring-boot-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/kafeindb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    networks:
      - mynetwork

  react-app:
    image: kafein-frontend:latest
    container_name: react-app
    ports:
      - "80:3000"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork


volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
